apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: oci
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: helm
  helm:
    repo: oci://us-central1-docker.pkg.dev/anthos-gsd-lab-01/oci-repo
    chart: mysql
    version: 9.16.2
    releaseName: test-mysql
    namespace: test
    auth: gcpserviceaccount
    gcpServiceAccountEmail: oci-174@anthos-gsd-lab-01.iam.gserviceaccount.com
    values:
      image:
        pullPolicy: Always
      primary:
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
