apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: helm-chart-1
  namespace: config-management-system
spec:
  sourceType: helm
  sourceFormat: unstructured
  helm:
    repo: https://charts.bitnami.com/bitnami
    chart: nginx
    version: v15.4.2
    releaseName: nginx-bitnami
    namespace: nginx
    auth: none
